apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resilientcart
resources:
  - namespace.yaml
  - secret.demo.yaml
  - infrastructure.yaml
  - applications.yaml
  - hpa.yaml
configMapGenerator:
  - name: postgres-init
    files:
      - init.sql=postgres-init.sql
commonLabels:
  app.kubernetes.io/part-of: resilientcart
