apiVersion: v1
kind: Secret
metadata:
  name: resilientcart-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  RABBITMQ_DEFAULT_USER: resilientcart
  RABBITMQ_DEFAULT_PASS: resilientcart
  AMQP_URL: amqp://resilientcart:resilientcart@rabbitmq:5672/%2F
  ORDER_DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/orderdb
  INVENTORY_DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/inventorydb
  PAYMENT_DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/paymentdb
  NOTIFICATION_DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/notificationdb
